spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
kafka:
  server_addr: ${KAFKA_SERVER_ADDRESS}

---

spring:
  config:
    activate:
      on-profile: test
kafka:
  server_addr: ${TEST_KAFKA_SERVER_ADDRESS}
